/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 monitor.gltf
Author: hoschu (https://sketchfab.com/hoschu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c64-monitor-b005d2125a1545ad9e0994e0deb5e82e
Title: C64 Monitor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Monitor(props) {
  const { nodes, materials } = useGLTF('/monitor.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_Default_0.geometry} material={materials.Default} />
    </group>
  )
}

useGLTF.preload('/monitor.gltf')
